# Generated by Django 5.0.2 on 2024-02-29 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('describtion', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movie Category',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OTP_COLLECTION_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('otp', models.IntegerField()),
                ('expireTime', models.DateTimeField()),
                ('No_of_times', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTP Collection',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=50)),
                ('describtion', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('release_date', models.DateTimeField()),
                ('actors', models.JSONField(null=True)),
                ('youtube_link', models.CharField(max_length=200)),
                ('created_at1', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.moviecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movies',
                'ordering': ['-created_at1'],
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at2', models.DateTimeField(auto_now_add=True)),
                ('likers', models.ManyToManyField(blank=True, related_name='BlogPostLikers', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_user', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_movie', to='myapp.movies')),
            ],
            options={
                'verbose_name': 'Movie Comments',
                'ordering': ['-created_at2'],
            },
        ),
    ]
