# Generated by Django 5.0.2 on 2024-03-01 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='BlogPostLikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
