# Generated by Django 5.0.2 on 2024-03-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_moviecomment_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
